### ISSUE TITLE
TypeScript 4.x support

### ISSUE THREAD

**Issue by ybiquitous** [hata6502/textlint-plugin-jsx#5]
Hi, do you have a plan to support TypeScript 4.x?

Currently, when installing `textlint-plugin-jsx`, TypeScript 3 is installed. But I use TypeScript 4 in my project.

https://github.com/hata6502/textlint-plugin-jsx/blob/d1e0f47a4041c2739dba16b16c996923ccaac984/package.json#L24

Maybe, it seems nice to me to move `typescript` to `peerDependencies` like this:

```json
{
  "peerDependencies": {
    "typescript": "3.x || 4.x"
  }
}
```

**Comment by hata6502** [comment]
Thanks for your feedback!
I released the fixed version.

npm: https://www.npmjs.com/package/textlint-plugin-jsx/v/1.1.2
commit: https://github.com/hata6502/textlint-plugin-jsx/commit/7b7029f61932d6b4cd3feeb13b54815211f6f71b

**Comment by ybiquitous** [comment]
@hata6502 Thank you very much! 😄
